/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : UDP
 #	author : miyako
 #	2016/04/04
 #
 # --------------------------------------------------------------------------------*/

#ifdef __APPLE__
#include <getopt.h>
#include <arpa/inet.h> 
#else
#include "getopt.h"
#define option option_a
#define getopt_long getopt_long_a
#define optarg optarg_a
#define close closesocket
#pragma comment(lib, "Ws2_32.lib")
#endif
#include <stdio.h>
#include <stdlib.h>
#include <vector>

// --- Client
void UDP_GET_SERVER_LIST(sLONG_PTR *pResult, PackagePtr pParams);
