/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : UDP
 #	author : miyako
 #	2014/06/24
 #
 # --------------------------------------------------------------------------------*/



// --- Client
void UDP_GET_SERVER_LIST(sLONG_PTR *pResult, PackagePtr pParams);
